version: '3'

services:
  db:
    image: postgres:16-alpine
    container_name: local_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - local_postgres_english

networks:
  local_postgres_english:
    driver: bridge

volumes:
  pgdata: